[package]
name = "gitviewr"
version = "0.1.0"
description = "Understand your Git repositories."
authors = ["PVK"]
edition = "2021"

[lib]
name = "gitviewr_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
git2 = { version = "0.21", features = ["https"] }
url = "2"
open = "5"

[dev-dependencies]
tempfile = "3"
tauri = { version = "2", features = ["test"] }
